[tool.poetry]
name = "bookbot"
version = "0.1.0"
description = ""
authors = ["PossibleNPC <28771786+PossibleNPC@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
